social_pro_main_homepage:
    path:     /
    defaults: { _controller: SocialProMainBundle:SocialPro:index }
mainpage:
    path:     /mainpage
    defaults: { _controller: SocialProMainBundle:SocialPro:mainpage }

profile2:
    path:     /profile2
    defaults: { _controller: SocialProMainBundle:SocialPro:profile2 }

parametresprofil:
    path:     /paraprofile
    defaults: { _controller: SocialProMainBundle:SocialPro:parametresprofil }


#_ _Start_Reclamation
index_Reclamation:
     path:     /reclamation
     defaults: { _controller: SocialProMainBundle:Reclamation:index }
ajouter_Reclamation:
    path:     /ajouterReclamation
    defaults: { _controller: SocialProMainBundle:Reclamation:ajouterReclamation }

afficher_Reclamation:
    path:     /afficherReclamation
    defaults: { _controller: SocialProMainBundle:Reclamation:afficherReclamation }

supprimer_Reclamation:
    path:     /supprimerReclamation/{id}
    defaults: { _controller: SocialProMainBundle:Reclamation:supprimerReclamation }

modifier_Reclamation:
    path:     /modifierReclamation/{id}
    defaults: { _controller: SocialProMainBundle:Reclamation:modifierReclamation }

valider_Reclamation:
    path:     /validerReclamation
    defaults: { _controller: SocialProMainBundle:Reclamation:supprimerReclamation }

rechercher_Reclamation:
    path:     /rechercherReclamation
    defaults: { _controller: SocialProMainBundle:Reclamation:rechercherReclamation }
#_ _End_Reclamation


#_ _Start_Evenement
index_Evenement:
     path:     /Evenement
     defaults: { _controller: SocialProMainBundle:Evenement:index }
ajouter_Evenement:
    path:     /ajouterEvenement
    defaults: { _controller: SocialProMainBundle:Evenement:ajouterEvenement }

afficher_Evenement:
    path:     /afficherEvenement
    defaults: { _controller: SocialProMainBundle:Evenement:afficherEvenement }

supprimer_Evenement:
    path:     /supprimerEvenement/{id}
    defaults: { _controller: SocialProMainBundle:Evenement:supprimerEvenement }

modifier_Evenement:
    path:     /modifierEvenement/{id}
    defaults: { _controller: SocialProMainBundle:Evenement:modifierEvenement }

valider_Evenement:
    path:     /validerEvenement
    defaults: { _controller: SocialProMainBundle:Evenement:validerEvenement }

rechercher_Evenement:
    path:     /rechercherEvenement
    defaults: { _controller: SocialProMainBundle:Evenement:rechercherEvenement }
#_ _End_Reclamation

